DROP TABLE IF EXISTS  columns;

CREATE TABLE columns (
  id: BIGINT GENERATED ALWAYS AS IDENTITY;
  title: TEXT;
  content: TEXT;
  created_at: DATE DEFAULT CURRENT_TIMESTAMP;
  published: BOOLEAN DEFAULT FALSE;
);

CREATE TABLE users (
	id BIGINT GENERATED ALWAYS AS IDENTITY,
	email TEXT UNIQUE NOT NULL,
	password_hash TEXT NOT NULL,
	first_name TEXT
);
